---
name: Feature request
description: Suggest an idea for this project
issue_body: false

body:
- type: markdown
  attributes:
    value: |
      ⚠
      Verify first that your feature/improvement is not [already suggested on GitHub][issue search].

      [issue search]: https://github.com/linode/ansible_linode/search?q=is%3Aissue&type=issues

- type: textarea
  attributes:
    label: Summary
    description: Describe the new feature/improvement briefly below.
  validations:
    required: true

- type: input
  attributes:
    label: Component Name
    description: >-
      Write the short name of the module, plugin, task or feature below,
    placeholder: instance, nodebalancer, volume, etc.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional Information
    description: |
      Describe how the feature would be used, why it is needed and what it would solve.

      **HINT:** You can paste https://gist.github.com links for larger files.
    value: |
      <!--- Paste example playbooks or commands between quotes below -->
      ```yaml (paste below)

      ```
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Code of Conduct
    description: |
      Read the [Ansible Code of Conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html?utm_medium=github&utm_source=issue_form--ansible-collections) first.
    options:
    - label: I agree to follow the Ansible Code of Conduct
      required: true
...
