name: Run Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: update packages
        run: sudo apt-get update -y

      - name: install make
        run: sudo apt-get install -y build-essential

      - name: setup python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: install dependencies
        run: pip3 install -r requirements-dev.txt -r requirements.txt ansible

      - name: install ansible dependencies
        run: ansible-galaxy collection install amazon.aws

      - name: install collection
        run: make install

      - name: copy makefile to installed collection
        run: cp Makefile ~/.ansible/collections/ansible_collections/linode/cloud/Makefile

      - name: copy tests to installed collection
        run: cp -r tests ~/.ansible/collections/ansible_collections/linode/cloud/tests

      - name: run tests
        run: cd ~/.ansible/collections/ansible_collections/linode/cloud && make test
        env:
          LINODE_API_TOKEN: ${{ secrets.DX_LINODE_TOKEN }}